Print SQLException.getNextException()s as suppressed exceptions
If the next exceptions are not printed, the logged exception is usually not as useful, e.g.
java.sql.BatchUpdateException: Batch entry 0 [SQL] was aborted.  Call getNextException to see the cause.